### ISSUE TITLE
WITH DATA CATEGORY Clauses are not supported

### ISSUE THREAD

**Issue by ABenassi87** [paustint/soql-parser-js#26] opened 2018-10-14 13:56 UTC
- [ ] Feature
- [x] Bug Request

## Description
Queries that include WITH DATA CATEGORY clauses are displayed as invalid queries.

Examples from:  https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_with_datacategory_examples.htm

#### Query 1:
``` sql
SELECT Title FROM Question WHERE LastReplyDate < 2005-10-08T01:02:03Z WITH DATA CATEGORY Product__c AT mobile_phones__c
```
#### Query 2:
``` sql
SELECT Title, Summary FROM KnowledgeArticleVersion WHERE PublishStatus='Online' AND Language = 'en_US' WITH DATA CATEGORY Geography__c ABOVE_OR_BELOW europe__c AND Product__c BELOW All__c
```
#### Query 3:
``` sql
SELECT Id, Title FROM Offer__kav WHERE PublishStatus='Draft' AND Language = 'en_US' WITH DATA CATEGORY Geography__c AT (france__c,usa__c) AND Product__c ABOVE dsl__c
```

**Comment by paustint** [comment] 2018-10-14 21:29
duplicate of #18

**Closed by paustint** 2018-10-14 21:29 UTC
Labels: bug
